config/routes.rb
Askaway::Application.routes.draw do
  root to: 'questions#trending'

  devise_for :users, skip: :registrations, :path => '',
             :path_names => { :sign_in => "log_in", :sign_out => "log_out"},
             :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # Skipping registration and adding paths here in order to remove 'cancel' option
  as :user do
    get 'create_an_account' => 'devise/registrations#new', as: :new_user_registration
    post 'create_an_account' => 'devise/registrations#create', as: :user_registration
  end

  ActiveAdmin.routes(self)

  match '/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/search' => 'search#index'

  resources :users, only: :show do
    member do
      get :edit
      patch :update
      get :new_avatar
      patch :upload_avatar
      patch :select_avatar
    end
  end

  # get '/users/:id' => redirect("/u/%{id}")
  # get '/users/:id/:action' => redirect("/u/%{id}/%{action}")

  resources :questions, path: 'q', only: [:show, :new, :create] do
    resources :comments, only: :create
    resources :votes, only: :create
    resources :answers, only: :create
  end

  resources :comments, only: :destroy
  resources :votes, only: :destroy
  resources :answers, only: [:edit, :update] do
    member do
      get :history
    end
  end

  scope module: :admin do
    resources :embedded_topics, only: :index
  end

  scope '/rnz', module: :rnz_admin, as: 'rnz_admin' do
    get '/' => redirect('rnz/questions')
    resources :embedded_topics, except: [:destroy]
    resources :questions, only: [:index, :edit, :update] do
      member do
        patch :approve
        patch :unapprove
      end
    end
  end

  scope '/embed', module: :embed, as: 'embed' do
    resources :questions, only: [:show] do
      collection do
        get :trending
      end
    end
  end
  # get 'embedded_topics/admin', to: 'embedded_topics#admin'
  resources :embedded_topics, only: :show

  get 'new_questions', to: 'questions#new_questions'
  get 'trending', to: 'questions#trending'
  get 'most_votes', to: 'questions#most_votes'
  get 'recently_answered', to: 'questions#recently_answered'

  resources :parties, only: :show, path: 'p' do
    member do
      get :invited_reps
      get :walkthrough
      get :new_avatar
      patch :upload_avatar
    end
    resources :invitations, only: [:new, :create]
  end

  resources :invitations, only: [:show, :destroy]

  resources :placeholders, only: [:new, :create, :show] do
    member do
      get :new_avatar
      patch :upload_avatar
    end
  end

  post 'announcements/dismiss', to: 'announcements#dismiss'

  get 'about', to: 'pages#about', as: 'about'
  get 'terms_of_use', to: 'pages#terms_of_use', as: 'terms_of_use'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'

  get '/sitemap.xml.gz' => 'sitemaps#show'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  body        :text
#  rep_id      :integer
#  question_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Answer < ActiveRecord::Base
  BODY_MAX_LENGTH = 350

  belongs_to :rep, inverse_of: :answers
  belongs_to :question, inverse_of: :answers, touch: true, counter_cache: true

  after_create :notify_asker

  validates_presence_of :rep
  validates_presence_of :question
  validates_presence_of :body
  validates_length_of :body, maximum: BODY_MAX_LENGTH
  validates_uniqueness_of :rep_id, scope: [:question_id]
  validate :one_answer_per_party, on: :create

  has_paper_trail

  default_scope { order(created_at: :asc) }

  def rep_name
    rep.name
  end

  def rep_avatar
    rep.avatar
  end

  def rep_authorisation
    rep.authorisation
  end

  def is_edited?
    edited_at.present?
  end

  private
    def one_answer_per_party
      if Question.has_answer_from_party?(question, rep.party)
        errors.add(:rep, "This question has already been answered by the party.")
      end
    end

  def notify_asker
    AnswerMailer.asker_notification(self).deliver
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: :history
  before_action :check_site_closed_xhr, only: [:create]
  before_action :check_site_closed, only: [:edit, :update]

  def edit
    authorize(answer)
  end

  def update
    authorize(answer)
    answer.edited_at = Time.zone.now
    answer.body = params[:answer][:body]
    if answer.save(answer_params)
      flash[:notice] = 'Answer edited.'
      redirect_to answer.question
    else
      flash[:alert] = 'Answer could not be edited.'
      render 'edit'
    end
  end

  def history
    authorize(answer)
    answer
  end

  def create
    question = Question.friendly.find(params[:question_id])
    answer = Answer.new(body: params[:answer][:body],
                        question: question,
                        rep: current_user.rep)
    error_message = 'Could not post answer. It may have already been answered by someone from your party.'
    authorize answer
    if answer.save
      flash[:notice] = 'Answer posted.' unless request.xhr?
      redirect_to question
    elsif request.xhr?
      render json: { message: error_message }, status: 422
    else
      flash[:alert] = error_message
      redirect_to question
    end
  end

  private
    def check_site_closed_xhr
      if Setting.site_closed?
        error_message = 'Sorry, answering on Ask Away has closed.'
        return render json: { message: error_message }, status: 422
      end
    end

    def answer
      @answer ||= Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/views/answers/_answers_expanded.html.haml
%ul.answers-expanded(ng-show="question.answers_count > 0")
  %li.answers-expanded-item(ng-repeat="answer in question.answers")
    %div.media.comment.answer.answer-item
      %span.pull-left.answer-avatar-container
        %img.media-object.avatar.comment-avatar(ng-src="{{answer.rep_avatar}}")
        .answer-party-avatar
          %img(ng-src="{{answer.party_avatar}}")
      .media-body
        .comment-name
          %a(ng-href="{{answer.user_path}}") {{answer.rep}}
          %a(ng-href="{{answer.party_path}}") ({{answer.party}})
          .text-detail.comment-detail
            {{answer.created_at}}
            %span(ng-show='"{{answer.history_path}}"')
              ·
              %a(ng-href='{{answer.history_path}}') Edited
        .comment-body(ng-bind-html="answer.body | autolinker")
        .answer-footer.text-detail(ng-show="'{{answer.edit_path}}'")
          %a(ng-href="{{answer.edit_path}}") Edit
          %span(ng-show="'{{answer.convert_path}}'")
            ·
            %a(ng-href="{{answer.convert_path}}" data-method="put" data-confirm="Are you sure you want to convert this answer into a comment?") Convert

app/views/answers/_form.html.haml
.answer-form-container(ng-show="question.can_answer")
  - if Setting.site_closed?
    .text-detail Answering on Ask Away has closed.
  - else
    %div.media.comment.answer.answer-form
      %span.pull-left.hidden-xs
        %img.media-object.avatar.comment-avatar{src: current_user.try(:avatar_url) }
      .media-body
        %form(ng-controller='AnswerFormCtrl' ng-submit="addAnswer()" name="new_answer" dirtyconfirm="new_answer")
          .form-group
            %textarea.form-control.required#answer-text(ng-model="question.answerText" placeholder='Write your answer...' ng-disabled="question.error_message" name="answer_body")
            %charcounter(for_model="question.answerText" maxlength="350")
          .alert.alert-warning(ng-show="question.error_message")
            {{question.error_message}}
            %a(href ng-show="question.error_message" ng-click="loadQuestion()") (Reload question)

          %input.btn.btn-primary#post-answer(type="submit" ng-disabled="!question.answerText" ng-hide="question.error_message" data-disable-with="Post answer" value='Post answer')

app/views/answers/_share.html.haml
.modal.fade#share-answer-modal(ng-controller='AnswerFormCtrl')
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{:type => 'button', 'data-dismiss' => 'modal'}
          x
        %h4.modal-title Share your answer
      .modal-body
        Thanks! Now that you've done the hard work, let your voters know about your answer.
        %br
        %br
        .share-buttons

app/views/answers/edit.html.haml
.row
  .col-xs-12.col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading
        %h1.panel-title Edit answer
      .panel-body
        %p= @answer.question.body
        -#= render 'form', question: nil, answer: @answer, button_text: 'Update answer'
        %div(ng-controller='AnswerFormCtrl')
          = simple_form_for([@answer], html: { ng_controller: 'AnswerFormCtrl', name: "new_answer", dirtyconfirm:"new_answer", ng_submit: "submit()" }) do |f|
            = f.input :body, placeholder: 'Write your answer...', label_html: {class: 'sr-only'}, as: :charlimited, input_html: {ng_initial: true}
            = f.submit "Update answer", id: 'post-answer-btn', class: 'btn btn-primary', data: { disable_with: "Update answer" }

app/views/answers/history.html.haml
.row
  .col-xs-12.col-md-8.col-md-offset-2
    %h3
      Answer history
      %small= link_to '(Back to question)', question_path(@answer.question)
    %ul.list-group
      %li.list-group-item
        .media.answer
          %span.pull-left
            %img.media-object.avatar.comment-avatar{src: @answer.rep.user.avatar_url }
          .media-body
            .comment-name
              = link_to @answer.rep.name, @answer.rep.user
              %span.text-detail said

      - @answer.versions.each do |version|
        - next unless answer = version.reify
        %li.list-group-item
          .list-group-item-header.text-detail= answer.updated_at.strftime("%I:%M%p %d %B %Y %Z")
          .list-group-item-text.comment-body= simple_format(answer.body)

      %li.list-group-item
        .list-group-item-header.text-detail= @answer.updated_at.strftime("%I:%M%p %d %B %Y %Z")
        .list-group-item-text.comment-body= simple_format(@answer.body)