config/routes.rb
Askaway::Application.routes.draw do
  root to: 'questions#trending'

  devise_for :users, skip: :registrations, :path => '',
             :path_names => { :sign_in => "log_in", :sign_out => "log_out"},
             :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # Skipping registration and adding paths here in order to remove 'cancel' option
  as :user do
    get 'create_an_account' => 'devise/registrations#new', as: :new_user_registration
    post 'create_an_account' => 'devise/registrations#create', as: :user_registration
  end

  ActiveAdmin.routes(self)

  match '/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/search' => 'search#index'

  resources :users, only: :show do
    member do
      get :edit
      patch :update
      get :new_avatar
      patch :upload_avatar
      patch :select_avatar
    end
  end

  # get '/users/:id' => redirect("/u/%{id}")
  # get '/users/:id/:action' => redirect("/u/%{id}/%{action}")

  resources :questions, path: 'q', only: [:show, :new, :create] do
    resources :comments, only: :create
    resources :votes, only: :create
    resources :answers, only: :create
  end

  resources :comments, only: :destroy
  resources :votes, only: :destroy
  resources :answers, only: [:edit, :update] do
    member do
      get :history
    end
  end

  scope module: :admin do
    resources :embedded_topics, only: :index
  end

  scope '/rnz', module: :rnz_admin, as: 'rnz_admin' do
    get '/' => redirect('rnz/questions')
    resources :embedded_topics, except: [:destroy]
    resources :questions, only: [:index, :edit, :update] do
      member do
        patch :approve
        patch :unapprove
      end
    end
  end

  scope '/embed', module: :embed, as: 'embed' do
    resources :questions, only: [:show] do
      collection do
        get :trending
      end
    end
  end
  # get 'embedded_topics/admin', to: 'embedded_topics#admin'
  resources :embedded_topics, only: :show

  get 'new_questions', to: 'questions#new_questions'
  get 'trending', to: 'questions#trending'
  get 'most_votes', to: 'questions#most_votes'
  get 'recently_answered', to: 'questions#recently_answered'

  resources :parties, only: :show, path: 'p' do
    member do
      get :invited_reps
      get :walkthrough
      get :new_avatar
      patch :upload_avatar
    end
    resources :invitations, only: [:new, :create]
  end

  resources :invitations, only: [:show, :destroy]

  resources :placeholders, only: [:new, :create, :show] do
    member do
      get :new_avatar
      patch :upload_avatar
    end
  end

  post 'announcements/dismiss', to: 'announcements#dismiss'

  get 'about', to: 'pages#about', as: 'about'
  get 'terms_of_use', to: 'pages#terms_of_use', as: 'terms_of_use'
  get 'privacy_policy', to: 'pages#privacy_policy', as: 'privacy_policy'

  get '/sitemap.xml.gz' => 'sitemaps#show'
end

app/models/party.rb
# == Schema Information
#
# Table name: parties
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  auth_statement :string(255)
#  description    :text
#  created_at     :datetime
#  updated_at     :datetime
#

class Party < ActiveRecord::Base
  include FriendlyId
  def self.slug_candidate; :name; end
  friendly_id slug_candidate, :use => [:slugged, :history]
  include FriendlyIdHelper

  include UploadedAvatar

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :auth_statement

  has_many :reps
  has_many :rep_users, through: :reps, source: :user
  has_many :answers, through: :reps

  def invitations
    Invitation.to_join_party(self)
  end

  def pending_invitations
    invitations.where(accepted_at: nil)
  end

  def full_name
    "The #{name}"
  end

  def unassigned_topics
    @_unassigned_topics ||= calculate_unassigned_topics
  end

  def assigned_topics
    @_assigned_topics ||= calculate_assigned_topics
  end

  private
    def calculate_assigned_topics
      # FIXME: this should be done in SQL to be performant
      topics = []
      reps.assigned.each do |rep|
        topics += rep.topics
      end
      topics
    end

    def calculate_unassigned_topics
      # FIXME: this should be done in SQL to be performant
      assigned = []
      reps.each do |rep|
        assigned = assigned + rep.topics
      end
      Topic.all - assigned
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_filter :fetch_party_and_authorize

  def show
    @profile = ProfilePresenter.new(current_user, @party)
    @invitation = Invitation.new
    redirect_to_canonical_show_path(@party)

    @meta_title = "#{@party.name} - Answering your questions on Ask Away"
    @meta_description = "Ask the #{@party.name} questions and see their answers this New Zealand election."
    @meta_img = URI(request.url) + @party.avatar_url(size: :large)
  end

  def walkthrough; end

  def new_avatar
    @resource = @party
    @title = "Upload a profile picture for #{@party.name}"
    render 'users/new_avatar'
  end

  def upload_avatar
    @resource = @party
    perform_avatar_upload(path_for_redirect: party_path(@party))
  end

  private
    def fetch_party_and_authorize
      @party ||= Party.friendly.find(params[:id])
      authorize @party
    end
end

app/views/profiles/parties/_spokespeople.html.haml
%ul.reps-list.list-group
  - record.rep_users.order(name: :asc).each do |rep_user|
    %li.list-group-item
      .media
        %a.pull-left{href: user_path(rep_user)}
          %img.media-object.avatar{src: rep_user.avatar_url }
        .media-body= link_to rep_user.name, rep_user
  - if current_user.try(:can_administer?, record)
    - record.pending_invitations.order('created_at ASC').each do |invitation|
      %li.list-group-item
        .media
          .pull-left
            %img.media-object.avatar{src: record.avatar_url(size: :small)}
          .media-body
            .list-group-item-heading.gray-light #{invitation.name} (invited)
            .list-group-item-text.text-detail
              = link_to 'Copy invitation link', '#', data: {toggle: 'modal', target: '#resend-invitation'}, ng_click: "invitation.url = '#{invitation_url(invitation.token)}'; invitation.name = '#{invitation.name}'"
              |
              = link_to 'Delete', invitation_path(invitation), method: :delete, data: {confirm: 'Are you sure you want to delete the invitation?'}
    %li.list-group-item
      .list-group-item-heading Invite someone to represent #{record.name}
      .list-group-item-body
        = simple_form_for([record, @invitation], html: {class: 'form-inline'}) do |f|
          = f.input :name, placeholder: 'Full Name', label_html: {class: 'sr-only'}
          = f.input :email, placeholder: 'Email', label_html: {class: 'sr-only'}
          = f.submit 'Invite', data: {disable_with: 'Invite'}, class: 'btn btn-primary'

#resend-invitation.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        %h3.modal-title Copy invitation link
      .modal-body
        = text_field_tag :invitation_link, "{{invitation.url}}", :onclick => 'this.select();', class: 'form-control'
        .help-block Manually email this link to {{invitation.name}} to re-invite them to #{record.name}.
      .modal-footer
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>